---
- name: Converge false-modules
  hosts: all
  gather_facts: false

  vars:
    python_pip_modules:
      - name: jinja2
      - name: ansible

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - ansible-role-python-pip
