---
# tasks file for python-pip
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_pip_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(python_pip_packages[ansible_distribution]
      | default(python_pip_packages['default'] )) }}"

- name: update pip
  pip:
    name: pip
    state: present
    version: "{{ python_pip_version }}"

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ python_pip_modules }}"
