---
# tasks file for python-pip
- name: install python-pip
  package:
    name: python-pip
    state: present

- name: update pip
  pip:
    name: pip
    state: latest

- name: install modules
  pip:
    name: pyyaml
