---
# tasks file for python-pip
- name: install python-pip
  package:
    name: python-pip
    state: present
  when:
    - ( ansible_distribution == "CentOS" or ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )

- name: install py-pip
  package:
    name: py-pip
    state: present
  when:
    - ansible_distribution == "Alpine"

- name: update pip
  pip:
    name: pip
    state: latest

- name: install modules
  pip:
    name: pyyaml
