---
# tasks file for python-pip
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install python-pip or py-pip
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: update pip
  pip:
    name: pip
    state: latest

- name: install modules
  pip:
    name: pyyaml
