---
# tasks file for python_pip
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ python_pip_packages }}"

- name: update pip
  pip:
    name: pip
    version: 18.0
  register: update_pip
  until: update_pip is succeeded
  retries: 3

- name: update setuptools
  pip:
    name: setuptools
    version: 40.2.0
  register: update_setuptools
  until: update_setuptools is succeeded
  retries: 3

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ python_pip_modules }}"
  register: install_requested_modules
  until: install_requested_modules is succeeded
  retries: 3
