---
# tasks file for python_pip
- name: install python pip
  package:
    name: "{{ python_pip_packages[ansible_distribution]
          | default(python_pip_packages['default']) }}"
    state: "{{ python_pip_package_state }}"

- name: update pip
  pip:
    name: pip
    state: present
    version: 18.0
  register: update_pip
  until: update_pip is succeeded
  retries: 3

- name: update setuptools
  pip:
    name: setuptools
    state: present
    version: 40.2.0
  register: update_setuptools
  until: update_setuptools is succeeded
  retries: 3

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ python_pip_modules }}"
  register: install_requested_modules
  until: install_requested_modules is succeeded
  retries: 3
