---
# tasks file for python_pip
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_pip_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(python_pip_packages[ansible_distribution]
      | default(python_pip_packages['default'] )) }}"

- name: update pip
  pip:
    name: pip
    version: "{{ python_pip_version }}"
  register: update_pip
  until: update_pip is succeeded
  retries: 3

- name: update setuptools
  pip:
    name: setuptools
    version: "{{ python_pip_setuptools_version }}"
  register: update_setuptools
  until: update_setuptools is succeeded
  retries: 3

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ python_pip_modules }}"
  register: install_requested_modules
  until: install_requested_modules is succeeded
  retries: 3
