---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-python-pip
      python_pip_modules:
        - name: jinja2
        - name: ansible
