---
- name: Converge no-modules
  hosts: all
  gather_facts: no
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.scl
    - role: ansible-role-python-pip
      python_pip_modules:
        - name: jinja2
